version: "3"

services:
  redis:
    image: "redis:5.0.5"
  webserver:
    image: ghcr.io/espoirmur/airflow-for-tweets:deploy-to-new-server
    restart: always
    depends_on:
      - redis
    env_file:
      - ./.env
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8083:8080"
    command: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/
  flower:
    image: ghcr.io/espoirmur/airflow-for-tweets:deploy-to-new-server
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    command: flower
  scheduler:
    image: ghcr.io/espoirmur/airflow-for-tweets:deploy-to-new-server
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/
    env_file:
      - ./.env
    command: airflow scheduler
  worker:
    image: ghcr.io/espoirmur/airflow-for-tweets:deploy-to-new-server
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/
    env_file:
      - ./.env
    command: airflow worker
  streamlit-instance:
    image: ghcr.io/espoirmur/airflow-for-tweets:deploy-to-new-server
    restart: always
    depends_on:
      - worker
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW_HOME=/home/es.py/
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    command: streamlit run stream_it.py
