version: "3"
services:
  webserver:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    env_file: ./.env.dev
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8080:8080"
    environment:
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini
    mem_limit: 768m
  scheduler:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini/
    mem_limit: 256m
    env_file: ./.env.dev
    command: airflow scheduler
  worker:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini
    env_file: ./.env.dev
    command: airflow celery worker
    mem_limit: 768m
  streamlit-instance:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - worker
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW_HOME=/home/es.py/balobi_nini
    env_file: ./.env.dev
    command: streamlit run stream_it.py
    mem_limit: 256m
    ports:
      - "8501:8501"
