version: "3"

services:
  webserver:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./dags:/usr/local/airflow/dags
    network_mode: host
    command: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini
  scheduler:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini/
    env_file:
      - ./.env
    command: airflow scheduler
    network_mode: host
  worker:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - EXECUTOR=Celery
      - LC_ALL="en_US.UTF-8"
      - LC_CTYPE="en_US.UTF-8"
      - AIRFLOW_HOME=/home/es.py/balobi_nini
    env_file:
      - ./.env
    command: airflow celery worker
    network_mode: host

  streamlit-instance:
    image: ghcr.io/espoirmur/airflow-for-tweets:latest
    restart: always
    depends_on:
      - worker
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW_HOME=/home/es.py/balobi_nini
    env_file:
      - ./.env
    command: streamlit run stream_it.py
    network_mode: host
